firstWebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('<int:user_id>/vote/', views.vote, name='vote'),

    path('<int:pk>/scoreboard/', views.ScoreboardView.as_view(), name='scoreboard'),
]

posts/models.py
from django.db import models


class User(models.Model):
    bio = models.CharField(max_length = 255)
    age = models.IntegerField()
    skillLevel = models.CharField(max_length = 100)
    location = models.CharField(max_length = 1000)

    def __str__(self):
        return self.bio + ' : ' + self.skillLevel


class Post(models.Model):
    User =  models.ForeignKey(User, on_delete= models.CASCADE)
    subject = models.CharField(max_length = 100)
    currentLoc = models.CharField(max_length = 1000)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.subject

posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import User, Post
from django.shortcuts import render,  get_object_or_404
from django.urls import reverse


class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'list_all_users'

    def get_queryset(self):
        """Return the top users based off skill level"""
        return User.objects.all()


class DetailView(generic.DetailView):
    model = User
    template_name = 'posts/detail.html'


def vote(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    try:
        selected_post = user.post_set.get(pk=request.POST['post_id'])
    except (KeyError, Post.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'posts/detail.html', {
            'user': user,
            'error_message': "You didn't select a post.",
        })
    else:
        selected_post.likes += 1
        selected_post.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('posts:scoreboard', args=(user.id,)))


class ScoreboardView(generic.DetailView):
    model = User
    template_name = 'posts/scoreboard.html'

posts/templates/posts/detail.html
<h1>{{ user.bio }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'posts:vote' user.id %}" method="post">
{% csrf_token %}
{% for post in user.post_set.all %}
    <label>{{ post.subject }}</label><br>
    <button name="post_id" type="submit" value="{{ post.id }}" class ="btn btn-primary">Like</button><br>
{% endfor %}
</form>

posts/templates/posts/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">

{% if list_all_users %}

    <ul>
        {% for user in list_all_users %}
        <li><a href="{% url 'posts:detail' user.id %}">{{user.bio}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3> You don't have any friends </h3>
{% endif %}

posts/templates/posts/scoreboard.html
<h1>{{ user.bio }}</h1>

<ul>
{% for post in user.post_set.all %}
    <li>{{ post.subject }} -- {{ post.likes }} like{{ post.likes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'posts:detail' user.id %}">Vote again?</a>